## Estruturação de arquivos CSV com a proporção de população inscrita no Bolsa Família nos anos de 2023 e 2024, para cada município brasileiro.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df_bolsa_familia_2023 = pd.read_csv("/content/bolsa_familia_2023.csv", delimiter=';')
df_bolsa_familia_2024 = pd.read_csv("/content/bolsa_familia_2024.csv", delimiter=';')
df_populacao = pd.read_csv("/content/br_ibge_populacao_municipio.csv")
df_city_code = pd.read_csv("/content/br_bd_diretorios_brasil_municipio.csv")

In [ ]:
df_bolsa_familia_2023.head()

   Código Unidade Territorial  UF  Referência  Pessoas beneficiárias
0  120001          ACRELÂNDIA  AC        2023                   7216
1  120005        ASSIS BRASIL  AC        2023                   6833
2  120010           BRASILÉIA  AC        2023                  13495
3  120013              BUJARI  AC        2023                   6285
4  120017            CAPIXABA  AC        2023                   6125

In [ ]:
df_bolsa_familia_2023 = df_bolsa_familia_2023.filter(items=["Unidade Territorial", "UF", "Pessoas beneficiárias"]).rename(columns={"Unidade Territorial": "municipio", "UF": "sigla_uf"})
df_bolsa_familia_2023['municipio'] = df_bolsa_familia_2023['municipio'].str.upper()
df_bolsa_familia_2023.head()

      municipio sigla_uf  Pessoas beneficiárias
0    ACRELÂNDIA       AC                   7216
1  ASSIS BRASIL       AC                   6833
2     BRASILÉIA       AC                  13495
3        BUJARI       AC                   6285
4      CAPIXABA       AC                   6125

In [ ]:
df_bolsa_familia_2024.head()

,Código,Unidade Territorial,UF,Referência,Pessoas beneficiárias no PBF (até Out/2021),Pessoas beneficiárias no PBF (a partir de Mar/2023)
0,120001,ACRELÂNDIA,AC,2024,NaN,6954
1,120005,ASSIS BRASIL,AC,2024,NaN,7038
2,120010,BRASILÉIA,AC,2024,NaN,13503
3,120013,BUJARI,AC,2024,NaN,6458
4,120017,CAPIXABA,AC,2024,NaN,5937

In [ ]:
df_bolsa_familia_2024 = df_bolsa_familia_2024.filter(items=["Unidade Territorial", "UF", "Pessoas beneficiárias no PBF (a partir de Mar/2023)"]).rename(columns={"Unidade Territorial": "municipio", "UF": "sigla_uf", "Pessoas beneficiárias no PBF (a partir de Mar/2023)": "Pessoas beneficiárias"})
df_bolsa_familia_2024['municipio'] = df_bolsa_familia_2024['municipio'].str.upper()
df_bolsa_familia_2024.head()

      municipio sigla_uf  Pessoas beneficiárias
0    ACRELÂNDIA       AC                   6954
1  ASSIS BRASIL       AC                   7038
2     BRASILÉIA       AC                  13503
3        BUJARI       AC                   6458
4      CAPIXABA       AC                   5937

In [ ]:
df_populacao_2023 = df_populacao[df_populacao['ano'] == 2023]
df_populacao_2023.head()

    ano sigla_uf  id_municipio  populacao
0  2023       RO       1100015      21494
1  2023       RO       1100023      96833
2  2023       RO       1100031       5351
3  2023       RO       1100049      86887
4  2023       RO       1100056      15890

In [ ]:
df_populacao_2024 = df_populacao[df_populacao['ano'] == 2024]
df_populacao_2024.head()

       ano sigla_uf  id_municipio  populacao
5570  2024       RO       1100015      22853
5571  2024       RO       1100023     108573
5572  2024       RO       1100031       5690
5573  2024       RO       1100049      97637
5574  2024       RO       1100056      16975

In [ ]:
df_city_code['nome'] = df_city_code['nome'].str.upper()
df_city_code.head()

   id_municipio                    nome sigla_uf
0       5101837  BOA ESPERANÇA DO NORTE       MT
1       1100809      CANDEIAS DO JAMARI       RO
2       1100338             NOVA MAMORÉ       RO
3       1100205             PORTO VELHO       RO
4       1101104         ITAPUÃ DO OESTE       RO

In [ ]:
df_populacao_2023 = df_populacao_2023.merge(df_city_code, how='left', left_on='id_municipio', right_on='id_municipio').filter(items=['nome', 'sigla_uf_x', 'populacao']).rename(columns={'sigla_uf_x': 'sigla_uf', 'nome':'municipio'})

In [ ]:
df_populacao_2024 = df_populacao_2024.merge(df_city_code, how='left', left_on='id_municipio', right_on='id_municipio').filter(items=['nome', 'sigla_uf_x', 'populacao']).rename(columns={'sigla_uf_x': 'sigla_uf', 'nome':'municipio'})

In [ ]:
df_bolsa_familia_2023.isna().sum()

municipio                0
sigla_uf                 0
Pessoas beneficiárias    0
dtype: int64

In [ ]:
df_bolsa_familia_2024.isna().sum()

municipio                0
sigla_uf                 0
Pessoas beneficiárias    0
dtype: int64

In [ ]:
df_populacao_2023.isna().sum()

municipio    0
sigla_uf     0
populacao    0
dtype: int64

In [ ]:
df_populacao_2024.isna().sum()

municipio    0
sigla_uf     0
populacao    0
dtype: int64

In [ ]:
proporcao_2023 = df_bolsa_familia_2023.merge(df_populacao_2023, how='left', on=['municipio', 'sigla_uf'])
proporcao_2023['proporcao'] = (proporcao_2023['Pessoas beneficiárias'] / proporcao_2023['populacao']).round(2)
proporcao_2023.head()

      municipio sigla_uf  Pessoas beneficiárias  populacao  proporcao
0    ACRELÂNDIA       AC                   7216      14021       0.51
1  ASSIS BRASIL       AC                   6833       8100       0.84
2     BRASILÉIA       AC                  13495      26000       0.52
3        BUJARI       AC                   6285      12917       0.49
4      CAPIXABA       AC                   6125      10392       0.59

In [ ]:
proporcao_2023[proporcao_2023['populacao'].isna()]

Empty DataFrame
Columns: [municipio, sigla_uf, Pessoas beneficiárias, populacao, proporcao]
Index: []

In [ ]:
proporcao_2023.to_csv("br_proporcao_pbf_2023.csv")

In [ ]:
proporcao_2024 = df_bolsa_familia_2024.merge(df_populacao_2024, how='left', on=['municipio', 'sigla_uf'])
proporcao_2024["proporcao"] = (proporcao_2024["Pessoas beneficiárias"] / proporcao_2024["populacao"]).round(2)
proporcao_2024.head()

      municipio sigla_uf  Pessoas beneficiárias  populacao  proporcao
0    ACRELÂNDIA       AC                   6954      14657       0.47
1  ASSIS BRASIL       AC                   7038       8573       0.82
2     BRASILÉIA       AC                  13503      27841       0.49
3        BUJARI       AC                   6458      13766       0.47
4      CAPIXABA       AC                   5937      10922       0.54

In [ ]:
proporcao_2024[proporcao_2024['populacao'].isna()]

Empty DataFrame
Columns: [municipio, sigla_uf, Pessoas beneficiárias, populacao, proporcao]
Index: []

In [ ]:
proporcao_2024.to_csv("br_proporcao_pbf_2024.csv")